spring:
  application:
    name: config
    desc: SpringCloud config project
    version: 4.0.0
    packageName: com.aaron

  cloud:
    config:
      server:
        git:
          uri: https://github.com/AaronSheng/springcloud-server.git
          search-paths: config/{application}/

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8085/eureka/

server:
  port: 8082